### ISSUE TITLE
Show wrong hdmi input

### ISSUE THREAD

**Issue by mafyata** [tavicu/homebridge-samsung-tv#150]
Hi , I have a problem only when watching from hdmi. It does’t show that I am at hdmi. If I watch hbo go or youtube and open home app it shows them correct. The problem is at ios13. 
![7FE5E433-92FA-4F32-A404-9C4C75008848](https://user-images.githubusercontent.com/48009267/67887587-3bc37280-fb54-11e9-8592-3d81f1727c32.jpeg)

**Comment by tavicu** [comment]
https://github.com/tavicu/homebridge-samsung-tizen/issues?utf8=✓&q=is%3Aissue+hdmi+

**Comment by mafyata** [comment]
> https://github.com/tavicu/homebridge-samsung-tizen/issues?utf8=✓&q=is%3Aissue+hdmi+

???
