### ISSUE TITLE
this.config.value.startsWith is not a function

### ISSUE THREAD

**Issue by zackwag** [tavicu/homebridge-samsung-tv#497]
When using plugin >= 5.20, the plugin fails at startup with the message

```
[3/14/2022, 9:20:30 AM] [SamsungTizen] this.config.value.startsWith is not a function
```

**Comment by tavicu** [comment]
Show me your config, the inputs part.

**Comment by zackwag** [comment]
The `value` field was deleted somehow (?). I reconfigured and everything works again. Sorry. Thanks for the help!

**Comment by hkdan** [comment]
Hi Tavicu,
first of all thanks for the great work on this plugin. I am experiencing the same issue. After updating to the newest version I get the same message and the home app is showing 'no response'. Configuration stays the same after the update, nothing is deleted. Downgrading to 5.1.2 brings back the functionality. The inputs part is:
"inputs": [
                        {
                            "name": "Live TV",
                            "type": "command",
                            "value": [
                                "KEY_SOURCE",
                                "KEY_DOWN",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        },
                        {
                            "name": "Apple TV",
                            "type": "command",
                            "value": [
                                "KEY_SOURCE",
                                "KEY_DOWN",
                                "KEY_RIGHT",
                                "KEY_RIGHT",
                                "KEY_ENTER"
                            ]
                        }]

Thanks in advance for your help.

**Comment by tavicu** [comment]
Hi @hkdan,

Thank you! I forgot the type `command` supports array! I have pushed a new version which fix it!
Also, you could switch to input sting and use comma like this:

```
{
    "name": "Apple TV",
    "type": "command",
    "value": "KEY_SOURCE, KEY_DOWN, KEY_RIGHT, KEY_RIGHT, KEY_ENTER"
}
```

And don't forget we just release integration with SmartThings :) so no need for hacks anymore!
https://github.com/tavicu/homebridge-samsung-tizen/wiki/Inputs#input-type-input

**Comment by hkdan** [comment]
Hi @tavicu,

thank you very much for your super quick help. Works again :) 

Yes, I saw the integration, great news. Will try to do this tomorrow :) Again, thank you very much for letting me control the tv even when the kids have lost the remote :)

**Comment by tavicu** [comment]
> Yes, I saw the integration, great news. Will try to do this tomorrow :) Again, thank you very much for letting me control the tv even when the kids have lost the remote :)

He he :D! I'm glad you enjoy it! Try to put an airtag on the remote.
